### ISSUE TITLE
Output of a task generateAvroJava without explicit or implicit dependency

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [davidmc24/gradle-avro-plugin#195] opened 2022-04-06 11:21 UTC
**Prerequisites**

* [x] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases))
* [x] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [x] Are you reporting to the correct repository?  If your schema doesn't work with the Apache Avro CLI tool either, it's not a problem with this plugin.  Running your file through the `CLIComparisonTest` in the sample project under the `test-project` directory can help diagnose this.
* [x] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

**Describe the bug**

I have kotlin project where I am using avro plugin alongside ktlint (kotlint linter).
When I run build, following log message appears:
```
Task :runKtlintCheckOverMainSourceSet
Execution optimizations have been disabled for task ':runKtlintCheckOverMainSourceSet' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/aleksander.brzozowsk/IdeaProjects/education/avro-ktlint-gradle/build/generated-main-avro-java'. Reason: Task ':runKtlintCheckOverMainSourceSet' uses this output of task ':generateAvroJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

**To Reproduce**

The example repository with minimum configuration is available [here](https://github.com/AleksanderBrzozowski/avro-ktlint-gradle-problem).

**Expected behavior**

Log message should not appear. It should be fixed either in avro plugin or in ktlint plugin.

**Environment (please complete the following information):**
 - Gradle Version [7.4.1]
 - Apache Avro Version [-]
 - Gradle-Avro Plugin Version [1.3.0]
 - Java Version [11.0.7]
 - OS: [Mac OS X Big Sur]

**Comment by davidmc24** [comment] 2022-04-06 12:26
Thank you for the detailed issue report.  I especially appreciate the example repository.  I'll investigate the cause and get back to you.

**Comment by davidmc24** [comment] 2022-04-06 19:31
As stated in the [gradle docs](https://docs.gradle.org/7.4.1/userguide/validation_problems.html#implicit_dependency), this occurs when one task depends on another without an implicit or explicit dependency.

As a workaround until a fix is in place, you can explicitly declare a dependency between the tasks in your build.  For the example repository, this would be:

```groovy
runKtlintCheckOverMainSourceSet.dependsOn generateAvroJava
```

gradle-avro-plugin has no way to be aware of all tasks that may use the files it generates.

Next, I'll try to figure out the ktlint plugin is using the generated source dir, and why Gradle isn't treating it as an implicit dependency.

**Comment by AleksanderBrzozowski** [comment] 2022-04-06 19:35
Yes, you are right, I fixed this with:
```
tasks.named("runKtlintCheckOverMainSourceSet").configure { dependsOn(":generateAvroJava") }
```

I think that the plugin is using generated source dir, because we added it to main source sets:
```
sourceSets {
    main {
        java {
            srcDir "${buildDir}/generated-main-avro-java/"
        }
    }
}
``` 

There is an option to exclude (filter) folder from linting, but I tried it, and it didn't work :)

**Comment by AleksanderBrzozowski** [comment] 2022-04-07 06:31
@davidmc24 wow, thanks ;) Let me know if you will find something :)

**Comment by davidmc24** [comment] 2022-04-07 14:43
Unfortunately, I wasn't able to make any real progress on that front.  There probably is *something* that the ktlint plugin could do to better handle generated source directories, but I can't figure out what.

**Closed** 2022-09-07 03:31 UTC
Labels: bug
