### ISSUE TITLE
Can't find the latest release 0.17.0

### ISSUE THREAD

**Issue by khanhassan** [davidmc24/gradle-avro-plugin#96] opened 2019-11-14 15:50 UTC
Hi,

I can't find the latest release (0.17.0) in gradle repo. 

https://plugins.gradle.org/search?term=avro

When will you push it?

Regards

**Comment by davidmc24** [comment] 2019-11-14 16:16
Duplicate of #77.  This project no longer publishes new versions to the Gradle Plugin Portal, as said portal doesn't provide adequate download statistics.

**Closed by davidmc24** 2019-11-14 16:16 UTC
Labels: duplicate
